検索結果画面で2回目以降の検索が反映されるように修正
traPtitech/traPortfolio-UI pull request #195
Opened 2024-07-08 06:38 UTC by Futadaruma

close #191

2024-07-08 06:50 UTC, mehm8128 commented on src/pages/SearchPage.vue
> +      <user-list :query="search ?? ''" />
ここで`:key="search"`すれば、UserList.vueで`watch`を使わなくてもsearchが変化したときに再取得できるはずです
https://arc.net/l/quote/cnfkhffg

2024-07-08 12:20 UTC, Pugma commented
@mehm8128
僕が一旦 `SearchPage.vue`で以下の実装をやってみたらしっかり更新時にクエリが飛んでそうだったんですが、これでよさそうじゃないですか…？
```ts
import { onMounted, watch, ref } from 'vue'
import { User } from '/@/lib/apis'

const search = useQuery('q')
const users = ref<User[]>((await apis.getUsers(undefined, search.value)).data)

watch(search, async () => {
  users.value = (await apis.getUsers(undefined, search.value)).data
})
```

2024-07-08 12:49 UTC, mehm8128 commented
普段あんまり使わなくて普通に`watch`の存在忘れてたので元issueではkey使う方法を提案してました(watchをそんなに知らないのでなんとも言えないけどコードが分かりづらくなりそうなイメージがある)
また、↓みたいにUserListをSuspenseで囲うと、再fetchする度にloadingが表示されるようになるのでそこらへんちゃんと書くならkeyを使って子コンポーネントで取得するようにする方がよさそうな気がします(多分提案してくれた書き方だと再fetch時にtop level awaitしてないのでApp.vueのSuspenseも効かなさそう？)
```vue
<suspense :key="search">
        <user-list :query="search ?? ''" :users="users" />
        <template #fallback>loading...</template>
      </suspense>
    </div>
```

僕はVueそんなに詳しいわけではないのでお任せします

2024-07-08 13:07 UTC, Futadaruma commented
複数のコードを比較してどちらが良いか判断できるほどの知識と技術がないので、どれにするか決めるのはお任せしたいです
keyの方法を提案してもらっていたのにwatchで実装したことに深い理由はなくて（そこまで考えれてなくて)、実装方法を色々と調べていたらwatchの記法を見つけて、飛びついてしまったような形です

2024-07-08 14:46 UTC, Pugma commented
あ〜、Suspenceが効かないのはそうですね…
色々再描画の手法も調べてみたんですが、新しめの情報があまり出てこなかったのであまり現実的な実装じゃないかもです

そうなるとめふもさんが提案してくださった実装のほうがよさそうですね

個人的には先に挙げたやり方で行けると思っていたので実装が軽いと想定しちゃってました

2024-07-10 07:52 UTC, mehm8128 commented on src/pages/SearchPage.vue
> +        <user-list :query="search ?? ''" :members="users" />
すみません僕が前に提示したコードが間違えてて、usersの取得をUserList.vue側で行うようにしてほしいです:pray:(明日ぷぐまくんが教えてくれるっぽいですが、僕のミスなので...)

2024-07-11 06:04 UTC, Pugma commented
/improve

2024-07-11 09:01 UTC, Pugma requested changes
僕もペアプロのときにチェック漏れが発生していてお手数をかけて申し訳ないんですが、この変更をお願いします…！

2024-07-11 09:01 UTC, Pugma commented on src/pages/SearchPage.vue
> +        <user-list :query="query ?? ''" :search="query ?? ' '" />
不必要なqueryを消してほしいと伝え忘れていたんですが、これもお願いします！
```suggestion
        <user-list :query="query ?? ''" />
```

2024-07-11 09:01 UTC, Pugma commented on src/components/Search/UserList.vue
> +  search: string
あわせてこちらの名称も変更をお願いします
```suggestion
  query: string
```

2024-07-11 11:04 UTC, mehm8128 approved these changes
よさそうです、ありがとうございます:kansya_kansya:

2024-07-11 11:15 UTC, Pugma approved these changes
修正依頼にも応えてくれてありがとうございます！
お疲れさまでした

2024-07-11 11:27 UTC, merged