user の description を複数行に対応させた
traPtitech/traPortfolio-UI pull request #196
Opened 2024-07-08 08:46 UTC by Kaki256

2024-07-08 09:06 UTC, Pugma requested changes
改行の反映自体はできてるんですが、ここだけ確認をお願いします！
MDNのリンクも貼ってあるので見てみてください

2024-07-08 09:06 UTC, Pugma commented on src/components/User/BioContainer.vue
> +  white-space: pre-wrap;
AIは`word-break: break-word;`をおすすめしてるけど、これは今使われてない (https://developer.mozilla.org/ja/docs/Web/CSS/word-break#break-word すぐ横にゴミ箱アイコンがついてる) そうなので、MDNでこのすぐ下にあるnote2つ目にある`overflow-wrap: anywhere;` (https://developer.mozilla.org/ja/docs/Web/CSS/overflow-wrap#anywhere) を代わりに付与して欲しいです！
とても長い英単語 (スペース区切りのないひとかたまり) が来た際に今のままだと溢れてしまいそうです

2024-07-09 07:42 UTC, ogu-kazemiya approved these changes

2024-07-09 07:44 UTC, Pugma approved these changes
修正もやってくれてありがとうございます
マージしちゃってください！

2024-07-09 07:47 UTC, merged