rimrafのpackageを消した
traPtitech/traPortfolio-UI pull request #216
Opened 2024-08-28 01:27 UTC by sh0go07

2024-08-28 01:31 UTC, Pugma requested changes
lint が落ちてるので修正をお願いします！

2024-08-28 03:46 UTC, sh0go07 commented
これ lint が落ちてるのって本来消す必要がなかった node_module まで消えてるから？

2024-08-28 04:00 UTC, Pugma commented
今回のやつ、`npm uninstall rimraf` だけ叩いてやった？

2024-08-28 04:01 UTC, sh0go07 commented
そうね、`npm uninstall rimraf` でいけるとおもった

2024-08-28 04:02 UTC, Pugma commented
何で僕が手元でコマンド叩いたときと `package-lock.json` に差分が生じるんだろ

2024-08-28 04:03 UTC, Pugma commented
あと、CI で動いてる ESLint のバージョンが `package.json` と一致してなさそうなのでちょっと調査します

2024-08-28 09:07 UTC, Pugma commented
ん？ESLint 実行時に `--cache` をつけてキャッシュを効かせようとすると `rimraf` が必要なのか
Dashboard だとこれが有効化されてなかったから通ってたらしい

2024-10-24 16:11 UTC, nokhnaton commented
lint通しておきました～:8bit_sunglasses:

2024-10-24 17:04 UTC, Pugma approved these changes
nokhnaton さんありがとうございました！
バージョン更新で依存関係が修正されてそうでしたね

2024-10-24 17:04 UTC, merged